name: gnn-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Keep your same Python 3.10.14 series
  - python=3.10.14

  # Keep cudatoolkit 11.3.1
  - cudatoolkit=11.3.1

  # Keep same PyTorch version with CUDA 11.3
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda

  # Common numeric / data libraries
  - numpy
  - pandas
  - scikit-learn
  - geopy
  - xarray
  - requests
  - tqdm

  # minimal environment for your train + eval scripts
  - pip

  # PyTorch Geometric and its Scatter/Sparse sub-libs installed via pip
  - pip:
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-geometric==2.5.3
